version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: autoecole
      POSTGRES_USER: auto_user
      POSTGRES_PASSWORD: auto_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # optionnel en local (utile si tu veux accéder avec pgAdmin)
    restart: unless-stopped

  web:
    build: .
    depends_on:
      - db
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py loaddata status.json session_types.json session_activities.json notification_types.json licences_types.json countries.json governorates.json cities.json &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      DATABASE_URL: postgresql://auto_user:auto_pass@db:5432/autoecole
    restart: unless-stopped

volumes:
  pgdata:
