# Generated by Django 4.0.5 on 2022-07-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Marwa', max_length=30)),
                ('updated_by', models.CharField(default='Marwa', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(max_length=30, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('restored_at', models.DateTimeField(auto_now=True, null=True)),
                ('restored_by', models.CharField(default='Marwa', max_length=30, null=True)),
                ('name', models.CharField(max_length=100)),
                ('adress', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('governorate', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('tel', models.IntegerField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
