# Generated by Django 4.0.5 on 2024-06-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='car',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='card',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='session',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='activity',
        ),
        migrations.AddField(
            model_name='session',
            name='activities',
            field=models.CharField(choices=[('Acitvity 1', 'Acitvity 1'), ('Acitvity 2', 'Acitvity 2'), ('Acitvity 3', 'Acitvity 3'), ('Acitvity 4', 'Acitvity 4'), ('Acitvity 5', 'Acitvity 5'), ('Acitvity 6', 'Acitvity 6'), ('Acitvity 7', 'Acitvity 7')], default='Acitvity 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='autoecole_api.student'),
        ),
    ]
