# Generated by Django 4.0.5 on 2022-07-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='created_by',
            field=models.CharField(default='Ibiza', max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='restored_by',
            field=models.CharField(default='Ibiza', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_by',
            field=models.CharField(default='Ibiza', max_length=30),
        ),
    ]
