# Generated by Django 4.0.5 on 2024-08-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars', verbose_name='photo de profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fonction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guest'), (2, 'Admin'), (3, 'Owner'), (4, 'Trainer'), (5, 'Student')], default=1),
        ),
    ]
