# Generated by Django 4.2 on 2025-08-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0002_alter_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='owner',
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoecole_api.city'),
        ),
    ]
