# Generated by Django 4.0.5 on 2022-07-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0003_alter_school_deleted_at_alter_school_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='school',
            name='adress',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Ibiza', max_length=30)),
                ('updated_by', models.CharField(default='Ibiza', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('governorate', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('schools', models.ManyToManyField(to='autoecole_api.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
