# Generated by Django 4.2 on 2024-10-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0003_alter_notification_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(choices=[('car', 'Car'), ('session', 'Session'), ('payment', 'Payment'), ('appointment', 'Appointment')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
