# Generated by Django 4.2 on 2024-10-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0004_notification_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_sent', 'user']},
        ),
        migrations.AddField(
            model_name='student',
            name='card_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='module',
            field=models.CharField(choices=[('car', 'Car'), ('session', 'Session'), ('payment', 'Payment'), ('appointment', 'Appointment'), ('student', 'student'), ('card', 'card')], max_length=50),
        ),
    ]
