# Generated by Django 4.2 on 2025-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0004_alter_employee_options_schoolpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpayment',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
