# Generated by Django 4.0.5 on 2024-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0005_alter_activity_managers_alter_car_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='male', max_length=50),
        ),
    ]
