# Generated by Django 4.2 on 2025-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0005_alter_schoolpayment_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolpayment',
            options={'ordering': ['school', '-date']},
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
