# Generated by Django 4.0.5 on 2024-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0005_alter_employee_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
