# Generated by Django 4.0.5 on 2024-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0006_employee_image_employee_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
