# Generated by Django 4.0.5 on 2024-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0006_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
