# Generated by Django 4.2 on 2024-10-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0006_alter_student_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='card_id',
            new_name='cin',
        ),
    ]
