# Generated by Django 4.0.5 on 2022-07-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0007_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
