# Generated by Django 4.0.5 on 2024-08-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0007_alter_employee_matricule_alter_employee_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('1', 'In progress'), ('2', 'Completed'), ('3', 'Canceled')], default='In progress', max_length=50),
        ),
    ]
