# Generated by Django 4.0.5 on 2024-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0008_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('1', 'In progress'), ('2', 'Completed'), ('3', 'Canceled')], default=1, max_length=50),
        ),
    ]
