# Generated by Django 4.0.5 on 2024-07-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0008_remove_session_activities_session_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='card',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='autoecole_api.card'),
            preserve_default=False,
        ),
    ]
