# Generated by Django 4.0.5 on 2022-07-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoecole_api', '0009_alter_student_options_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoecole_api.student', unique=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Ibiza', max_length=30)),
                ('updated_by', models.CharField(default='Ibiza', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(max_length=50)),
                ('governorate', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('schools', models.ManyToManyField(to='autoecole_api.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
