# Generated by Django 4.2 on 2025-08-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0009_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='school',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='autoecole_api.school'),
            preserve_default=False,
        ),
    ]
