# Generated by Django 4.0.5 on 2022-07-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0010_alter_card_student_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoecole_api.student'),
        ),
    ]
