# Generated by Django 4.2 on 2025-06-01 10:46

import autoecole_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0010_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='manual_price',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=autoecole_api.models.avatar_upload_to, verbose_name='photo de profile'),
        ),
    ]
