# Generated by Django 4.2 on 2025-08-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0010_car_is_active_alter_userpreference_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='school',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='autoecole_api.school'),
            preserve_default=False,
        ),
    ]
