# Generated by Django 4.2 on 2025-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0011_remove_card_manual_price_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.IntegerField(unique=True),
        ),
    ]
