# Generated by Django 4.0.5 on 2022-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0011_alter_card_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Manager', max_length=100),
        ),
    ]
