# Generated by Django 4.0.5 on 2024-07-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0011_alter_session_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, to='autoecole_api.activity'),
        ),
        migrations.AlterField(
            model_name='session',
            name='card',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='autoecole_api.card'),
            preserve_default=False,
        ),
    ]
