# Generated by Django 4.2 on 2024-08-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0011_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
    ]
