# Generated by Django 4.2 on 2025-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0011_session_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='motive',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
