# Generated by Django 4.0.5 on 2022-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0012_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Trainer', 'Trainer')], default='Manager', max_length=100),
        ),
    ]
