# Generated by Django 4.0.5 on 2024-07-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0012_alter_session_activities_alter_session_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='autoecole_api.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='employee',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='autoecole_api.employee'),
            preserve_default=False,
        ),
    ]
