# Generated by Django 4.2 on 2025-08-30 21:15

import autoecole_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0012_alter_payment_motive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolPayment',
            new_name='SchoolSubscription',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['marque'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['licence_type'], 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['day'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Gaz', 'Gaz'), ('Electric', 'Electric')], max_length=50, verbose_name='fuel type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='car',
            name='marque',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='purchase date'),
        ),
        migrations.AlterField(
            model_name='car',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoecole_api.school', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='car',
            name='serial_number',
            field=models.CharField(error_messages={'unique': 'A car with this serial number already exists.'}, max_length=50, unique=True, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99999999, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='card',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99999999, null=True, verbose_name='hour price'),
        ),
        migrations.AlterField(
            model_name='card',
            name='hours_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of hours'),
        ),
        migrations.AlterField(
            model_name='card',
            name='licence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licence_type', to='autoecole_api.licencetype', verbose_name='licence type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99999999, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='card',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_card', to='autoecole_api.school', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_at',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='autoecole_api.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='card',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=99999999, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardP', to='autoecole_api.card', verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='espéces', max_length=50, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='motive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='school',
            name='adress',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(error_messages={'unique': 'A school with this code already exists.'}, max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='governorate'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='speciality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='specialty'),
        ),
        migrations.AlterField(
            model_name='school',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='session',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='autoecole_api.car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='session',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='autoecole_api.card', verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='session',
            name='day',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='session',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_at',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='event_type',
            field=models.CharField(choices=[('session', 'Session'), ('other', 'other')], default='session', max_length=50, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='cancelled'),
        ),
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='session',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='autoecole_api.school', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_type', to='autoecole_api.sessiontype', verbose_name='session type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_at',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=autoecole_api.models.avatar_upload_to, verbose_name='profile photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this CIN already exists.'}, max_length=50, null=True, unique=True, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='autoecole_api.governorate', verbose_name='governorate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guest'), (2, 'Admin'), (3, 'Owner'), (4, 'Trainer'), (5, 'Student')], default=1, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='autoecole_api.school', verbose_name='school'),
        ),
    ]
