# Generated by Django 4.2 on 2025-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0012_alter_student_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tel',
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
