# Generated by Django 4.2 on 2025-09-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0013_rename_schoolpayment_schoolsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='school',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='school_notifications', to='autoecole_api.school'),
            preserve_default=False,
        ),
    ]
