# Generated by Django 4.2 on 2025-09-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0014_notification_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='school',
        ),
    ]
