# Generated by Django 4.0.5 on 2022-07-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0014_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['marque']},
        ),
        migrations.RemoveField(
            model_name='card',
            name='price',
        ),
        migrations.AddField(
            model_name='card',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='hours_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='manual_price',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
