# Generated by Django 4.2 on 2024-09-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0014_progress_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='autoecole_api.progress'),
            preserve_default=False,
        ),
    ]
