# Generated by Django 4.0.5 on 2024-07-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0014_sessiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_type', to='autoecole_api.sessiontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
