# Generated by Django 4.2 on 2024-09-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0015_card_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='autoecole_api.progress'),
        ),
    ]
