# Generated by Django 4.2 on 2025-06-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0015_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
