# Generated by Django 4.2 on 2025-09-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0015_remove_notification_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
