# Generated by Django 4.0.5 on 2024-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0015_session_session_type_alter_sessiontype_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencetype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='owner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='governorate',
        ),
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='adress',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='speciality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
