# Generated by Django 4.2 on 2025-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0016_remove_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
