# Generated by Django 4.0.5 on 2024-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0016_alter_licencetype_options_remove_owner_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
