# Generated by Django 4.2 on 2025-09-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0016_alter_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'A user with this CIN already exists.'}, max_length=50, null=True, verbose_name='CIN'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('school', 'cin'), name='uniq_user_school_cin'),
        ),
    ]
