# Generated by Django 4.0.5 on 2024-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0017_alter_owner_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='tel',
            field=models.IntegerField(unique=True),
            preserve_default=False,
        ),
    ]
