# Generated by Django 4.2 on 2025-06-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0017_alter_student_cin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
