# Generated by Django 4.2 on 2025-09-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0018_otpcode_otpcode_autoecole_a_user_id_6868cf_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubscription',
            name='trial',
            field=models.BooleanField(default=False),
        ),
    ]
