# Generated by Django 4.2 on 2025-07-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0019_alter_owner_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='event_type',
            field=models.CharField(choices=[('session', 'Session'), ('other', 'other')], default='session', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='autoecole_api.employee'),
        ),
    ]
