# Generated by Django 4.2 on 2025-07-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0020_session_event_type_session_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='autoecole_api.card'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_type', to='autoecole_api.sessiontype'),
        ),
    ]
