# Generated by Django 4.2 on 2024-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0020_alter_cardstatushistory_options_alter_session_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='activities',
        ),
        migrations.AddField(
            model_name='session',
            name='activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
