# Generated by Django 4.2 on 2025-07-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0021_alter_session_card_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='autoecole_api.card'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='session_type', to='autoecole_api.sessiontype'),
        ),
    ]
