# Generated by Django 4.2 on 2025-07-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0022_alter_session_card_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='autoecole_api.card'),
        ),
        migrations.AlterField(
            model_name='session',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='autoecole_api.employee'),
        ),
    ]
