# Generated by Django 4.2 on 2025-08-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0024_device_notificationdelivery_notification_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='provider',
            field=models.CharField(choices=[('expo', 'Expo'), ('fcm', 'FCM')], db_index=True, default='expo', max_length=10),
        ),
    ]
