# Generated by Django 4.2 on 2025-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0025_device_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
