# Generated by Django 4.2 on 2025-08-13 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0026_alter_notificationtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 13, 11, 40, 28, 584614, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
