# Generated by Django 4.2 on 2025-08-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoecole_api', '0027_notificationtype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='notificationtype',
            old_name='name',
            new_name='title',
        ),
    ]
