from django.contrib import admin
from autoecole_api.models import *
# Register your models here.
admin.site.register(User)
admin.site.register(School)
admin.site.register(Card)
admin.site.register(Activity)
admin.site.register(Session)
admin.site.register(Car)
admin.site.register(LicenceType)
admin.site.register(SessionType)
admin.site.register(Status)
admin.site.register(Payment)
admin.site.register(CardStatusHistory)
admin.site.register(Notification)
admin.site.register(UserNotificationPreference)
admin.site.register(NotificationType)
admin.site.register(Country)
admin.site.register(Governorate)
admin.site.register(City)
admin.site.register(Device)
admin.site.register(NotificationDelivery)
admin.site.register(SchoolPayment)
